python3 train.py exp_name="default"
python3 train.py train_param.negative_train_contrast=false exp_name="no_negative_train_contrast"
python3 train.py train_param.use_validation_first_5=false exp_name="no_use_validation_first_5"
python3 train.py train_param.negative_train_contrast=false train_param.use_validation_first_5=false exp_name="no_negative_no_val"
python3 train.py features.feature_types="pcen" exp_name="pcen"
python3 train.py features.feature_types="pcen@mfcc" exp_name="pcen@mfcc"
python3 train.py features.feature_types="logmel" exp_name="logmel"
python3 train.py features.feature_types="logmel@mfcc" exp_name="logmel@mfcc"
python3 train.py features.feature_types="logmel@delta_mfcc" exp_name="logmel@delta_mfcc"
python3 train.py features.embedding_dim=1024 exp_name="emb_dim_1024"
python3 train.py features.embedding_dim=512 exp_name="emb_dim_512"
python3 train.py features.embedding_dim=256 exp_name="emb_dim_256"
python3 train.py features.embedding_dim=128 exp_name="emb_dim_128"